"""initial migration

Revision ID: d479a93712d6
Revises: 
Create Date: 2018-07-18 18:06:55.415334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd479a93712d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ec2_disk')
    op.alter_column('ec2type', 'cpu',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ec2type', 'memory',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_ec2type_type'), 'ec2type', ['type'], unique=False)
    op.create_index(op.f('ix_ectype_type'), 'ectype', ['type'], unique=False)
    op.alter_column('rdstype', 'cpu',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rdstype', 'memory',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_rdstype_type'), 'rdstype', ['type'], unique=False)
    op.create_index(op.f('ix_sysconfig_manage_key'), 'sysconfig_manage', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sysconfig_manage_key'), table_name='sysconfig_manage')
    op.drop_index(op.f('ix_rdstype_type'), table_name='rdstype')
    op.alter_column('rdstype', 'memory',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rdstype', 'cpu',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_ectype_type'), table_name='ectype')
    op.drop_index(op.f('ix_ec2type_type'), table_name='ec2type')
    op.alter_column('ec2type', 'memory',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ec2type', 'cpu',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('ec2_disk',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='ec2_disk_pkey')
    )
    # ### end Alembic commands ###
