"""add ec2 table utilization field

Revision ID: fa9433af8112
Revises: d479a93712d6
Create Date: 2018-07-18 18:24:12.144147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9433af8112'
down_revision = 'd479a93712d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ec2', sa.Column('utilization', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ec2', 'utilization')
    # ### end Alembic commands ###
